name: little_victories
description: An application that will help you celebrate the Little Victories you have every day.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.1.0+2012

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Firebase Packages
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  firebase_analytics: ^9.0.5
  firebase_messaging: ^11.2.4
  firebase_crashlytics: ^2.4.5
  cloud_firestore: ^3.1.5

  # Utils Packages
  path_provider: ^2.0.8
  basic_utils: ^3.9.4
  page_transition: ^2.0.4
  flutter_social_content_share: ^1.0.2
  image_picker: ^0.8.4+4
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  double_back_to_close_app: ^2.1.0

  # Social Packages
  google_sign_in: ^5.2.1
  social_share: ^2.2.1
  share: ^2.0.4

  # Widget Packages
  expansion_tile_card: ^2.0.0
  confetti: ^0.6.0

  # Other Packages
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.3
  device_preview: ^1.0.0
  flutter_launcher_icons_maker: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/lv_logo_purple_circle.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

flutter_native_splash:
  color: "#8060c3"
  image: assets/lv_logo_transparent.png

android12: true
fullscreen: true
# flutter pub run flutter_native_splash:create

