name: little_victories
description: An application that will help you celebrate the Little Victories you have every day.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Version code is Major.Minor.Patch. ie. 2.1.2
# Version number follows the patch as double digits per version concatenated. ie. 201020
version: 2.2.0+202000

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Firebase Packages
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  firebase_analytics: ^10.0.2
  firebase_messaging: ^14.0.2
  firebase_crashlytics: ^3.0.2
  cloud_firestore: ^4.0.2

  # Utils Packages
  path_provider: ^2.0.8
  basic_utils: ^4.2.2
  page_transition: ^2.0.4
  flutter_social_content_share: ^1.0.2
  image_picker: ^0.8.4+4
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.1.0
  awesome_notifications: ^0.6.21
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0

  # Social Packages
  google_sign_in: ^5.2.1
  social_share: ^2.3.1

  # Widget Packages
  expansion_tile_card: ^2.0.0
  confetti: ^0.7.0
  intro_views_flutter: ^3.2.0

  # Other Packages
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.2
  device_preview: ^1.0.0
  flutter_launcher_icons_maker: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/lv_logo_purple_circle.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

flutter_native_splash:
  color: "#8060c3"
  image: assets/lv_logo_transparent.png
  fullscreen: true
  android_12:
    image: assets/lv_logo_transparent.png
    color: "#8060c3"
# flutter pub run flutter_native_splash:create

