name: little_victories
description: An application that will help you celebrate the Little Victories you have every day.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Version code is Major.Minor.Patch. ie. 2.1.2
# Version number follows the patch as double digits per version concatenated. ie. 201020
version: 2.3.1+203010

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # Firebase Packages
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1

  # Utils Packages
  path_provider: ^2.1.1
  basic_utils: ^5.6.0
  page_transition: ^2.1.0
  fluttertoast: ^8.2.4
  awesome_notifications: ^0.9.3+1
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  google_fonts: 5.1.0

  # Social Packages
  google_sign_in: ^6.2.0
  sign_in_with_apple: ^5.0.0

  # Widget Packages

  simple_animations: ^5.0.2
  confetti: ^0.7.0
  intro_views_flutter: ^3.2.0
  avatar_glow: ^3.0.1
  progress_loading_button: ^2.0.2
  another_flutter_splash_screen: ^1.2.1
  lottie: ^3.1.0
  grouped_list: ^5.1.2
  auto_size_text: ^3.0.0
  day_night_time_picker: ^1.3.1

  # Other Packages
  google_mobile_ads: ^5.0.0
  in_app_purchase: ^3.1.13
  dotenv: ^4.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/logo_purple_circle.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#8060c3"
  image: assets/logo.png
  fullscreen: true
  android_12:
    image: assets/logo.png
    color: "#8060c3"
# flutter pub run flutter_native_splash:create

