// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB13OuV7yrjoac8NbC3usw6UQgAATzcSTo',
    appId: '1:33556680240:web:cc4d19689200a17782e7f5',
    messagingSenderId: '33556680240',
    projectId: 'little-victories-b2c60',
    authDomain: 'little-victories-b2c60.firebaseapp.com',
    databaseURL: 'https://little-victories-b2c60.firebaseio.com',
    storageBucket: 'little-victories-b2c60.appspot.com',
    measurementId: 'G-9BNV98SW8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXs7qBwEGIOs98mCBvRu3k7jJM1llFtdI',
    appId: '1:33556680240:android:79f48e2f6f3dffd182e7f5',
    messagingSenderId: '33556680240',
    projectId: 'little-victories-b2c60',
    databaseURL: 'https://little-victories-b2c60.firebaseio.com',
    storageBucket: 'little-victories-b2c60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYrsPud5se3JMhLbaT1tj_l2e-SYAlhYk',
    appId: '1:33556680240:ios:8cd8b9d425787da882e7f5',
    messagingSenderId: '33556680240',
    projectId: 'little-victories-b2c60',
    databaseURL: 'https://little-victories-b2c60.firebaseio.com',
    storageBucket: 'little-victories-b2c60.appspot.com',
    androidClientId: '33556680240-04s7a0jokgcajr8bnm6ce8ia8poiai1l.apps.googleusercontent.com',
    iosClientId: '33556680240-nu7224r69nfsod9hbv6mrkecqpevlblv.apps.googleusercontent.com',
    iosBundleId: 'rphenderson.dev.littleVictories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYrsPud5se3JMhLbaT1tj_l2e-SYAlhYk',
    appId: '1:33556680240:ios:8cd8b9d425787da882e7f5',
    messagingSenderId: '33556680240',
    projectId: 'little-victories-b2c60',
    databaseURL: 'https://little-victories-b2c60.firebaseio.com',
    storageBucket: 'little-victories-b2c60.appspot.com',
    androidClientId: '33556680240-04s7a0jokgcajr8bnm6ce8ia8poiai1l.apps.googleusercontent.com',
    iosClientId: '33556680240-nu7224r69nfsod9hbv6mrkecqpevlblv.apps.googleusercontent.com',
    iosBundleId: 'rphenderson.dev.littleVictories',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB13OuV7yrjoac8NbC3usw6UQgAATzcSTo',
    appId: '1:33556680240:web:388cc0cf035e66c782e7f5',
    messagingSenderId: '33556680240',
    projectId: 'little-victories-b2c60',
    authDomain: 'little-victories-b2c60.firebaseapp.com',
    databaseURL: 'https://little-victories-b2c60.firebaseio.com',
    storageBucket: 'little-victories-b2c60.appspot.com',
    measurementId: 'G-GP69T4CD3J',
  );
}
