name: Build develop
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'oracle'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      
      - name: Install Dependencies
        run: flutter pub get

      # Android
      - name: Build APK
        run: flutter build apk

      - name: Build AppBundle
        run: flutter build appbundle

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Modify Tag
        if: env.TAG_EXISTS == 'true'
        id: modify_tag
        run: |
          new_version="${{ env.VERSION }}-build-${{ github.run_number }}"
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios_build.tar.gz"
          tag: v${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}
